### PR TITLE
report attendance by day

### LINKED ISSUE #15: Report - Attendance by day
Report - Attendance by day

### PR DESCRIPTION
**Pull request by MrCano369x**
What did you implemented:
 We implement the attendance by day report, (view and controller)

## Screenshot
screen

### CODE REVIEW

**Review by AlejandroCuriel — APPROVED** [review]
LGTM :rocket: :eagle:

**Review by juperameza — APPROVED** [review]
LGTM !!

**Comment by nallely64** [comment]
LGTM <3

**Review by EliasUR — APPROVED** [review]
LGTM, cuevas el presentismo 😨

**Pull request merged**
